import {
  User,
  Subject,
  Question,
  QuestionCategory,
  ExamSession,
  StudentAttempt,
  StudentAccommodation,
  ComplianceRegulation,
  AuditLog,
  SchoolSettings,
  BadgeDefinition,
  StudentPracticeActivity,
} from '../types/index.ts';

export const initialSchoolSettings: SchoolSettings = {
  schoolName: 'Internationale Deutsche Schule Sarajevo',
  schoolCode: 'IDSS-OS-71000',
  cantonMinistry: 'Ministarstvo za odgoj i obrazovanje Kantona Sarajevo - Prosvjetno-pedagoški zavod',
  academicYear: '2025/2026',
  passingThresholdPercent: 50,
  examPeriodTitle: 'Eksterna matura za učenike IX razreda - Ispitni rok 2026.',
  commissionPresident: 'Prof. dr. Ismar Hadžiosmanović',
  schoolDirector: 'Mag. Thomas Weber (Direktor škole)',
  pedagogueName: 'Prof. Lejla Babić (Pedagog-psiholog)',
  address: 'Radnička bb / Grbavica, 71000 Sarajevo, Bosna i Hercegovina',
  contactEmail: 'sekretarijat@idss.ba',
  contactPhone: '+387 33 812-400',
};

export const initialUsers: User[] = [
  {
    id: 'user-superadmin-1',
    email: 'direktor@idss.ba',
    fullName: 'Mag. Thomas Weber',
    role: 'superadmin',
    status: 'active',
    phone: '+387 33 812-401',
    createdAt: '2025-09-01T08:00:00Z',
  },
  {
    id: 'user-admin-pedagog',
    email: 'pedagog@idss.ba',
    fullName: 'Prof. Lejla Babić',
    role: 'admin',
    status: 'active',
    phone: '+387 33 812-402',
    createdAt: '2025-09-01T08:30:00Z',
  },
  {
    id: 'user-admin-prof',
    email: 'matematika@idss.ba',
    fullName: 'Prof. Damir Kovačević',
    role: 'admin',
    status: 'active',
    phone: '+387 33 812-403',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'user-admin-deutsch',
    email: 'deutsch@idss.ba',
    fullName: 'Frau Sabine Müller (DaF/DSD)',
    role: 'admin',
    status: 'active',
    phone: '+387 33 812-404',
    createdAt: '2025-09-01T09:15:00Z',
  },
  {
    id: 'user-student-1',
    email: 'amar.hadzic@ucenik.idss.ba',
    fullName: 'Amar Hadžić',
    role: 'student',
    status: 'active',
    className: 'IX-1 (9a)',
    studentIdNumber: 'IDSS-IX-2026-001',
    phone: '+387 62 101-202',
    createdAt: '2025-09-10T10:00:00Z',
  },
  {
    id: 'user-student-2',
    email: 'sarah.mesic@ucenik.idss.ba',
    fullName: 'Sarah Mešić',
    role: 'student',
    status: 'active',
    className: 'IX-1 (9a)',
    studentIdNumber: 'IDSS-IX-2026-002',
    phone: '+387 62 303-404',
    createdAt: '2025-09-10T10:15:00Z',
  },
  {
    id: 'user-student-3',
    email: 'dino.begic@ucenik.idss.ba',
    fullName: 'Dino Begić',
    role: 'student',
    status: 'active',
    className: 'IX-2 (9b)',
    studentIdNumber: 'IDSS-IX-2026-003',
    phone: '+387 62 505-606',
    createdAt: '2025-09-10T10:30:00Z',
  },
  {
    id: 'user-student-4',
    email: 'emina.dzafic@ucenik.idss.ba',
    fullName: 'Emina Džafić',
    role: 'student',
    status: 'active',
    className: 'IX-2 (9b)',
    studentIdNumber: 'IDSS-IX-2026-004',
    phone: '+387 62 707-808',
    createdAt: '2025-09-10T11:00:00Z',
  },
  {
    id: 'user-student-5',
    email: 'felix.schneider@ucenik.idss.ba',
    fullName: 'Felix Schneider',
    role: 'student',
    status: 'active',
    className: 'IX-1 (9a)',
    studentIdNumber: 'IDSS-IX-2026-005',
    phone: '+387 62 909-010',
    createdAt: '2025-09-10T11:15:00Z',
  },
];

export const initialSubjects: Subject[] = [
  {
    id: 'sub-bhs',
    code: 'BHS-IX',
    name: 'Bosanski, hrvatski, srpski jezik i književnost',
    description: 'Nastavni plan IX razreda OŠ: morfologija, pravopis, sintaksa složene rečenice i književna lektira',
    durationMinutes: 90,
    totalPoints: 100,
    passingThresholdPercent: 50,
    isMandatory: true,
    color: 'emerald',
    topics: ['Morfologija i glagolski oblici', 'Pravopis i glasovne promjene', 'Sintaksa nezavisnih i zavisnih rečenica', 'Književnost i analiza teksta'],
  },
  {
    id: 'sub-mat',
    code: 'MAT-IX',
    name: 'Matematika',
    description: 'Nastavni plan IX razreda OŠ: brojevi, linearne jednačine i nejednačine, Pitagorina teorema, mnogouglovi i geometrijska tijela',
    durationMinutes: 90,
    totalPoints: 100,
    passingThresholdPercent: 50,
    isMandatory: true,
    color: 'blue',
    topics: ['Linearne jednačine i nejednačine', 'Pitagorina teorema i primjena', 'Površina i zapremina tijela', 'Procenti, proporcije i statistika'],
  },
  {
    id: 'sub-deu',
    code: 'DEU-IX',
    name: 'Njemački jezik / Deutsch (DSD I / DaF)',
    description: 'IDSS kurikulum za IX razred: njemački jezik kao prvi i drugi jezik, DSD I priprema, nivo A2/B1',
    durationMinutes: 90,
    totalPoints: 100,
    passingThresholdPercent: 50,
    isMandatory: true,
    color: 'amber',
    topics: ['Grammatik (Perfekt, Präteritum, Passiv)', 'Nebensätze (weil, dass, wenn)', 'Leseverstehen & Textanalyse', 'Wortschatz & Alltagskommunikation'],
  },
  {
    id: 'sub-eng',
    code: 'ENG-IX',
    name: 'Engleski jezik',
    description: 'Nastavni plan IX razreda OŠ: vremena, modalni glagoli, razumijevanje teksta i vokabular nivoa A2/B1',
    durationMinutes: 90,
    totalPoints: 100,
    passingThresholdPercent: 50,
    isMandatory: true,
    color: 'indigo',
    topics: ['Verb Tenses & Conditionals', 'Reading Comprehension', 'Passive Voice & Modals', 'Vocabulary & Phrasal Verbs'],
  },
  {
    id: 'sub-fiz',
    code: 'FIZ-IX',
    name: 'Fizika',
    description: 'Nastavni plan IX razreda OŠ: mehanika kretanja, rad i snaga, pritisak u fluidima i električna struja',
    durationMinutes: 90,
    totalPoints: 100,
    passingThresholdPercent: 50,
    isMandatory: false,
    color: 'cyan',
    topics: ['Kinematika i dinamika', 'Pritisak i Arhimedov zakon', 'Rad, energija i snaga', 'Električni napon, otpor i Ohmov zakon'],
  },
];

// Hierarchical category tree for Grade 9 curriculum at IDSS
export const initialCategories: QuestionCategory[] = [
  // Matematika hierarchy (IX razred osnovne škole)
  { id: 'cat-mat-root', name: 'Matematika', slug: 'matematika', subjectId: 'sub-mat', path: ['Matematika'] },
  { id: 'cat-mat-alg', name: 'Linearne jednačine i nejednačine', slug: 'linearne-jednacine', subjectId: 'sub-mat', parentId: 'cat-mat-root', path: ['Matematika', 'Linearne jednačine i nejednačine'] },
  { id: 'cat-mat-geom', name: 'Pitagorina teorema i geometrija', slug: 'geometrija-pitagora', subjectId: 'sub-mat', parentId: 'cat-mat-root', path: ['Matematika', 'Pitagorina teorema i geometrija'] },
  { id: 'cat-mat-tijela', name: 'Geometrijska tijela (Prizma, Valjak, Kupa)', slug: 'geometrijska-tijela', subjectId: 'sub-mat', parentId: 'cat-mat-root', path: ['Matematika', 'Geometrijska tijela'] },
  { id: 'cat-mat-proc', name: 'Procenti, proporcije i statistika', slug: 'procenti-statistika', subjectId: 'sub-mat', parentId: 'cat-mat-root', path: ['Matematika', 'Procenti, proporcije i statistika'] },

  // B/H/S hierarchy (IX razred osnovne škole)
  { id: 'cat-bhs-root', name: 'B/H/S jezik i književnost', slug: 'bhs-jezik', subjectId: 'sub-bhs', path: ['B/H/S jezik i književnost'] },
  { id: 'cat-bhs-morf', name: 'Morfologija i glagolski oblici', slug: 'morfologija-glagoli', subjectId: 'sub-bhs', parentId: 'cat-bhs-root', path: ['B/H/S jezik i književnost', 'Morfologija i glagolski oblici'] },
  { id: 'cat-bhs-prav', name: 'Pravopis i glasovne promjene', slug: 'pravopis-leksika', subjectId: 'sub-bhs', parentId: 'cat-bhs-root', path: ['B/H/S jezik i književnost', 'Pravopis i glasovne promjene'] },
  { id: 'cat-bhs-sint', name: 'Sintaksa složene rečenice', slug: 'sintaksa-slozene-recenice', subjectId: 'sub-bhs', parentId: 'cat-bhs-root', path: ['B/H/S jezik i književnost', 'Sintaksa složene rečenice'] },
  { id: 'cat-bhs-knjiz', name: 'Književnost i lektira IX razreda', slug: 'knjizevnost', subjectId: 'sub-bhs', parentId: 'cat-bhs-root', path: ['B/H/S jezik i književnost', 'Književnost i lektira IX razreda'] },

  // Njemački jezik / Deutsch (DSD I / DaF za učenike IDSS)
  { id: 'cat-deu-root', name: 'Deutsch als Fremdsprache (DaF / DSD I)', slug: 'deutsch', subjectId: 'sub-deu', path: ['Deutsch als Fremdsprache (DaF / DSD I)'] },
  { id: 'cat-deu-gram', name: 'Grammatik (Perfekt, Präteritum, Modalverben)', slug: 'grammatik', subjectId: 'sub-deu', parentId: 'cat-deu-root', path: ['Deutsch als Fremdsprache (DaF / DSD I)', 'Grammatik (Perfekt, Präteritum, Modalverben)'] },
  { id: 'cat-deu-satz', name: 'Nebensätze (weil, dass, wenn, obwohl)', slug: 'nebensaetze', subjectId: 'sub-deu', parentId: 'cat-deu-root', path: ['Deutsch als Fremdsprache (DaF / DSD I)', 'Nebensätze (weil, dass, wenn, obwohl)'] },
  { id: 'cat-deu-lese', name: 'Leseverstehen & Wortschatz (DSD I Niveau A2/B1)', slug: 'leseverstehen', subjectId: 'sub-deu', parentId: 'cat-deu-root', path: ['Deutsch als Fremdsprache (DaF / DSD I)', 'Leseverstehen & Wortschatz (DSD I Niveau A2/B1)'] },

  // Engleski hierarchy (IX razred osnovne škole)
  { id: 'cat-eng-root', name: 'English Language', slug: 'english', subjectId: 'sub-eng', path: ['English Language'] },
  { id: 'cat-eng-gram', name: 'Grammar (Tenses, Conditionals, Modals)', slug: 'grammar', subjectId: 'sub-eng', parentId: 'cat-eng-root', path: ['English Language', 'Grammar'] },
  { id: 'cat-eng-voc', name: 'Vocabulary & Reading Comprehension', slug: 'vocabulary', subjectId: 'sub-eng', parentId: 'cat-eng-root', path: ['English Language', 'Vocabulary & Reading Comprehension'] },

  // Fizika hierarchy (IX razred osnovne škole)
  { id: 'cat-fiz-root', name: 'Fizika', slug: 'fizika', subjectId: 'sub-fiz', path: ['Fizika'] },
  { id: 'cat-fiz-meh', name: 'Mehanika kretanja i sila', slug: 'mehanika-kretanja', subjectId: 'sub-fiz', parentId: 'cat-fiz-root', path: ['Fizika', 'Mehanika kretanja i sila'] },
  { id: 'cat-fiz-el', name: 'Električna struja i Ohmov zakon', slug: 'elektricna-struja', subjectId: 'sub-fiz', parentId: 'cat-fiz-root', path: ['Fizika', 'Električna struja i Ohmov zakon'] },
];

export const initialQuestions: Question[] = [
  // BHS (IX razred)
  {
    id: 'q-bhs-1',
    subjectId: 'sub-bhs',
    topic: 'Morfologija i glagolski oblici',
    categoryId: 'cat-bhs-morf',
    categoryPath: ['B/H/S jezik i književnost', 'Morfologija i glagolski oblici'],
    tags: ['glagoli', 'potencijal', 'standardni-jezik', 'ix-razred', 'matura-2026'],
    questionText: 'U rečenici "Kada bi sutra došao, obradovao bi nas.", glagolski oblik "bi došao" predstavlja:',
    options: [
      { id: 'A', text: 'Pluskvamperfekat' },
      { id: 'B', text: 'Potencijal I (kondicional I)' },
      { id: 'C', text: 'Potencijal II (kondicional II)' },
      { id: 'D', text: 'Aorist' },
    ],
    correctOptionId: 'B',
    points: 2,
    difficulty: 'basic',
    cognitiveDomain: 'knowledge',
    explanation: 'Potencijal I (kondicional I) gradi se od aorista pomoćnog glagola "biti" (bih, bi, bi, bismo, biste, bi) i radnog glagolskog pridjeva.',
    authorName: 'Prof. Lejla Babić',
    isActive: true,
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'q-bhs-2',
    subjectId: 'sub-bhs',
    topic: 'Pravopis i glasovne promjene',
    categoryId: 'cat-bhs-prav',
    categoryPath: ['B/H/S jezik i književnost', 'Pravopis i glasovne promjene'],
    tags: ['pravopis', 'glasovne-promjene', 'asimilacija', 'osnovna-skola'],
    questionText: 'Koja od navedenih riječi je PRAVOPISNO TAČNO napisana prema važećoj pravopisnoj normi?',
    options: [
      { id: 'A', text: 'Predsjednik' },
      { id: 'B', text: 'Pretsjednik' },
      { id: 'C', text: 'Predtsjednik' },
      { id: 'D', text: 'Pretcjednik' },
    ],
    correctOptionId: 'A',
    points: 2,
    difficulty: 'basic',
    cognitiveDomain: 'knowledge',
    explanation: 'Iako se glas d ispred s u govoru asimilira, prema pravopisu ovdje ne dolazi do jednačenja po zvučnosti: "predsjednik".',
    authorName: 'Prof. Lejla Babić',
    isActive: true,
    createdAt: '2026-01-15T09:10:00Z',
    updatedAt: '2026-01-15T09:10:00Z',
  },
  {
    id: 'q-bhs-3',
    subjectId: 'sub-bhs',
    topic: 'Književnost i lektira IX razreda',
    categoryId: 'cat-bhs-knjiz',
    categoryPath: ['B/H/S jezik i književnost', 'Književnost i lektira IX razreda'],
    tags: ['lektira', 'camil-sijaric', 'bosanskohercegovacka-knjizevnost', 'ix-razred'],
    questionText: 'Koja od navedenih zbirki pripovijedaka pripada istaknutom piscu Ćamilu Sijariću, koja se obrađuje u lektiri IX razreda?',
    options: [
      { id: 'A', text: 'Bašta sljezove boje' },
      { id: 'B', text: 'Ram-Bulja' },
      { id: 'C', text: 'Kameni spavač' },
      { id: 'D', text: 'Gorke kapi' },
    ],
    correctOptionId: 'B',
    points: 2,
    difficulty: 'intermediate',
    cognitiveDomain: 'knowledge',
    explanation: 'Ćamil Sijarić je autor čuvene zbirke pripovijedaka "Ram-Bulja" (1953) i romana "Bihorci", obaveznih u lektiri završnih razreda osnovne škole.',
    authorName: 'Prof. Lejla Babić',
    isActive: true,
    createdAt: '2026-01-15T09:20:00Z',
    updatedAt: '2026-01-15T09:20:00Z',
  },
  {
    id: 'q-bhs-4',
    subjectId: 'sub-bhs',
    topic: 'Sintaksa složene rečenice',
    categoryId: 'cat-bhs-sint',
    categoryPath: ['B/H/S jezik i književnost', 'Sintaksa složene rečenice'],
    tags: ['sintaksa', 'zavisne-recenice', 'vremenska', 'ix-razred'],
    questionText: 'Odredi vrstu zavisne rečenice: "Čim je zazvonilo zvono, učenici su ušli u kabinet."',
    options: [
      { id: 'A', text: 'Namjerna rečenica' },
      { id: 'B', text: 'Vremenska rečenica' },
      { id: 'C', text: 'Uzročna rečenica' },
      { id: 'D', text: 'Načinska rečenica' },
    ],
    correctOptionId: 'B',
    points: 2,
    difficulty: 'intermediate',
    cognitiveDomain: 'comprehension',
    explanation: 'Veznik "čim" uvodi vremensku zavisnu rečenicu koja označava trenutak vršenja radnje glavne rečenice.',
    authorName: 'Prof. Lejla Babić',
    isActive: true,
    createdAt: '2026-01-15T09:30:00Z',
    updatedAt: '2026-01-15T09:30:00Z',
  },

  // MATEMATIKA (IX razred osnovne škole)
  {
    id: 'q-mat-1',
    subjectId: 'sub-mat',
    topic: 'Linearne jednačine i nejednačine',
    categoryId: 'cat-mat-alg',
    categoryPath: ['Matematika', 'Linearne jednačine i nejednačine'],
    tags: ['algebra', 'linearne-jednacine', 'ix-razred', 'osnovni-rok'],
    questionText: 'Riješi linearnu jednačinu: 3(x - 2) = 2(x + 4) - 5. Kolika je vrijednost nepoznate x?',
    options: [
      { id: 'A', text: 'x = 5' },
      { id: 'B', text: 'x = 9' },
      { id: 'C', text: 'x = 7' },
      { id: 'D', text: 'x = -3' },
    ],
    correctOptionId: 'B',
    points: 2,
    difficulty: 'basic',
    cognitiveDomain: 'application',
    explanation: '3x - 6 = 2x + 8 - 5 => 3x - 6 = 2x + 3 => 3x - 2x = 3 + 6 => x = 9.',
    authorName: 'Prof. Damir Kovačević',
    isActive: true,
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'q-mat-2',
    subjectId: 'sub-mat',
    topic: 'Pitagorina teorema i geometrija',
    categoryId: 'cat-mat-geom',
    categoryPath: ['Matematika', 'Pitagorina teorema i geometrija'],
    tags: ['pitagorina-teorema', 'trougao', 'hipotenuza', 'ix-razred', 'bez-kalkulatora'],
    questionText: 'Dužine kateta pravouglog trougla su a = 6 cm i b = 8 cm. Kolika je dužina hipotenuze c i obim trougla O?',
    options: [
      { id: 'A', text: 'c = 10 cm, O = 24 cm' },
      { id: 'B', text: 'c = 14 cm, O = 28 cm' },
      { id: 'C', text: 'c = 12 cm, O = 26 cm' },
      { id: 'D', text: 'c = 10 cm, O = 48 cm' },
    ],
    correctOptionId: 'A',
    points: 2,
    difficulty: 'basic',
    cognitiveDomain: 'application',
    explanation: 'Prema Pitagorinoj teoremi: c² = a² + b² = 6² + 8² = 36 + 64 = 100, pa je c = 10 cm. Obim je O = a + b + c = 6 + 8 + 10 = 24 cm.',
    authorName: 'Prof. Damir Kovačević',
    isActive: true,
    createdAt: '2026-01-20T10:15:00Z',
    updatedAt: '2026-01-20T10:15:00Z',
  },
  {
    id: 'q-mat-3',
    subjectId: 'sub-mat',
    topic: 'Geometrijska tijela (Prizma, Valjak, Kupa)',
    categoryId: 'cat-mat-tijela',
    categoryPath: ['Matematika', 'Geometrijska tijela'],
    tags: ['geometrijska-tijela', 'valjak', 'zapremina', 'ix-razred'],
    questionText: 'Pravi valjak ima poluprečnik baze r = 3 cm i visinu H = 10 cm. Kolika je zapremina (volumen) tog valjka?',
    options: [
      { id: 'A', text: '60π cm³' },
      { id: 'B', text: '90π cm³' },
      { id: 'C', text: '30π cm³' },
      { id: 'D', text: '180π cm³' },
    ],
    correctOptionId: 'B',
    points: 3,
    difficulty: 'intermediate',
    cognitiveDomain: 'application',
    explanation: 'Formula za zapreminu valjka je V = B * H = r²π * H = 3²π * 10 = 9π * 10 = 90π cm³.',
    authorName: 'Prof. Damir Kovačević',
    isActive: true,
    createdAt: '2026-01-20T10:30:00Z',
    updatedAt: '2026-01-20T10:30:00Z',
  },
  {
    id: 'q-mat-4',
    subjectId: 'sub-mat',
    topic: 'Procenti, proporcije i statistika',
    categoryId: 'cat-mat-proc',
    categoryPath: ['Matematika', 'Procenti, proporcije i statistika'],
    tags: ['procenti', 'cijena', 'tekstualni-zadatak', 'ix-razred', 'final-exam-review'],
    questionText: 'Knjiga je u knjižari prvobitno koštala 40 KM. Tokom proljetnog popusta cijena je snižena za 15%. Kolika je nova cijena knjige?',
    options: [
      { id: 'A', text: '32 KM' },
      { id: 'B', text: '34 KM' },
      { id: 'C', text: '35 KM' },
      { id: 'D', text: '36 KM' },
    ],
    correctOptionId: 'B',
    points: 3,
    difficulty: 'intermediate',
    cognitiveDomain: 'application',
    explanation: 'Iznos popusta je 15% od 40 KM = 0.15 * 40 = 6 KM. Nova cijena je 40 - 6 = 34 KM.',
    authorName: 'Prof. Damir Kovačević',
    isActive: true,
    createdAt: '2026-01-21T09:00:00Z',
    updatedAt: '2026-01-21T09:00:00Z',
  },

  // NJEMAČKI JEZIK / DEUTSCH (DSD I / DaF - IDSS)
  {
    id: 'q-deu-1',
    subjectId: 'sub-deu',
    topic: 'Grammatik (Perfekt, Präteritum, Modalverben)',
    categoryId: 'cat-deu-gram',
    categoryPath: ['Deutsch als Fremdsprache (DaF / DSD I)', 'Grammatik (Perfekt, Präteritum, Modalverben)'],
    tags: ['deutsch', 'perfekt', 'hilfsverben', 'dsd-1', 'a2-b1', 'idss'],
    questionText: 'Welches Hilfsverb ist grammatisch korrekt? "Gestern _______ wir nach Berlin geflogen."',
    options: [
      { id: 'A', text: 'haben' },
      { id: 'B', text: 'sind' },
      { id: 'C', text: 'werden' },
      { id: 'D', text: 'waren' },
    ],
    correctOptionId: 'B',
    points: 2,
    difficulty: 'basic',
    cognitiveDomain: 'knowledge',
    explanation: 'Das Verb "fliegen" drückt eine Ortsveränderung (Bewegung) aus und bildet das Perfekt im Deutschen mit dem Hilfsverb "sein": "wir sind geflogen".',
    authorName: 'Frau Sabine Müller (DaF/DSD)',
    isActive: true,
    createdAt: '2026-01-22T08:30:00Z',
    updatedAt: '2026-01-22T08:30:00Z',
  },
  {
    id: 'q-deu-2',
    subjectId: 'sub-deu',
    topic: 'Nebensätze (weil, dass, wenn, obwohl)',
    categoryId: 'cat-deu-satz',
    categoryPath: ['Deutsch als Fremdsprache (DaF / DSD I)', 'Nebensätze (weil, dass, wenn, obwohl)'],
    tags: ['deutsch', 'nebensaetze', 'wortstellung', 'weil', 'dsd-1', 'idss'],
    questionText: 'Welcher Satz hat die richtige deutsche Wortstellung im Nebensatz?',
    options: [
      { id: 'A', text: 'Felix lernt fleißig Deutsch, weil er will in Deutschland studieren.' },
      { id: 'B', text: 'Felix lernt fleißig Deutsch, weil er in Deutschland studieren will.' },
      { id: 'C', text: 'Felix lernt fleißig Deutsch, weil in Deutschland er studieren will.' },
      { id: 'D', text: 'Felix lernt fleißig Deutsch, weil er studieren in Deutschland will.' },
    ],
    correctOptionId: 'B',
    points: 2,
    difficulty: 'intermediate',
    cognitiveDomain: 'application',
    explanation: 'In einem deutschen Nebensatz mit der Konjunktion "weil" steht das konjugierte Verb (hier das Modalverb "will") ganz am Ende des Satzes (Verb-Letztstellung).',
    authorName: 'Frau Sabine Müller (DaF/DSD)',
    isActive: true,
    createdAt: '2026-01-22T09:00:00Z',
    updatedAt: '2026-01-22T09:00:00Z',
  },
  {
    id: 'q-deu-3',
    subjectId: 'sub-deu',
    topic: 'Leseverstehen & Wortschatz (DSD I Niveau A2/B1)',
    categoryId: 'cat-deu-lese',
    categoryPath: ['Deutsch als Fremdsprache (DaF / DSD I)', 'Leseverstehen & Wortschatz (DSD I Niveau A2/B1)'],
    tags: ['deutsch', 'dsd-1', 'leseverstehen', 'wortschatz', 'idss-schueler'],
    questionText: 'Was bedeutet das Wort "die Schulordnung" auf Bosnisch/Kroatisch/Serbisch?',
    options: [
      { id: 'A', text: 'Školski raspored časova' },
      { id: 'B', text: 'Školski kućni red / Pravila škole' },
      { id: 'C', text: 'Školska zgrada' },
      { id: 'D', text: 'Školski odbor' },
    ],
    correctOptionId: 'B',
    points: 2,
    difficulty: 'basic',
    cognitiveDomain: 'comprehension',
    explanation: '"Die Schulordnung" bezeichnet die Gesamtheit der Regeln und Verhaltensvorschriften an einer Schule (kućni red / pravilnik ponašanja u školi).',
    authorName: 'Frau Sabine Müller (DaF/DSD)',
    isActive: true,
    createdAt: '2026-01-22T09:30:00Z',
    updatedAt: '2026-01-22T09:30:00Z',
  },

  // ENGLESKI JEZIK (IX razred osnovne škole)
  {
    id: 'q-eng-1',
    subjectId: 'sub-eng',
    topic: 'Grammar (Tenses, Conditionals, Modals)',
    categoryId: 'cat-eng-gram',
    categoryPath: ['English Language', 'Grammar'],
    tags: ['grammar', 'first-conditional', 'a2-b1', 'ix-razred'],
    questionText: 'Choose the correct form to complete the sentence: "If it _______ tomorrow, the 9th grade students will stay indoors for the sports tournament."',
    options: [
      { id: 'A', text: 'rains' },
      { id: 'B', text: 'will rain' },
      { id: 'C', text: 'is raining' },
      { id: 'D', text: 'rained' },
    ],
    correctOptionId: 'A',
    points: 2,
    difficulty: 'basic',
    cognitiveDomain: 'application',
    explanation: 'In the First Conditional: If + Present Simple (rains), main clause with will + base form (will stay).',
    authorName: 'Prof. Lejla Babić',
    isActive: true,
    createdAt: '2026-01-22T10:00:00Z',
    updatedAt: '2026-01-22T10:00:00Z',
  },
  {
    id: 'q-eng-2',
    subjectId: 'sub-eng',
    topic: 'Vocabulary & Reading Comprehension',
    categoryId: 'cat-eng-voc',
    categoryPath: ['English Language', 'Vocabulary & Reading Comprehension'],
    tags: ['vocabulary', 'collocations', 'a2-b1', 'ix-razred'],
    questionText: 'Choose the correct verb that collocates with "an exam": "All 9th grade candidates must _______ the matriculation exam in June."',
    options: [
      { id: 'A', text: 'make' },
      { id: 'B', text: 'take' },
      { id: 'C', text: 'create' },
      { id: 'D', text: 'tell' },
    ],
    correctOptionId: 'B',
    points: 2,
    difficulty: 'basic',
    cognitiveDomain: 'knowledge',
    explanation: 'In English, we say "take an exam" or "sit an exam" (polagati ispit). "Make an exam" is incorrect.',
    authorName: 'Prof. Lejla Babić',
    isActive: true,
    createdAt: '2026-01-22T10:30:00Z',
    updatedAt: '2026-01-22T10:30:00Z',
  },

  // FIZIKA (IX razred osnovne škole)
  {
    id: 'q-fiz-1',
    subjectId: 'sub-fiz',
    topic: 'Električna struja i Ohmov zakon',
    categoryId: 'cat-fiz-el',
    categoryPath: ['Fizika', 'Električna struja i Ohmov zakon'],
    tags: ['ohmov-zakon', 'struja', 'otpor', 'ix-razred'],
    questionText: 'Kroz provodnik električnog otpora R = 5 Ω teče struja jačine I = 2 A. Koliki je električni napon U na krajevima tog provodnika?',
    options: [
      { id: 'A', text: '2.5 V' },
      { id: 'B', text: '7 V' },
      { id: 'C', text: '10 V' },
      { id: 'D', text: '20 V' },
    ],
    correctOptionId: 'C',
    points: 2,
    difficulty: 'basic',
    cognitiveDomain: 'application',
    explanation: 'Prema Ohmovom zakonu za dio strujnog kola: U = I * R = 2 A * 5 Ω = 10 V.',
    authorName: 'Prof. Damir Kovačević',
    isActive: true,
    createdAt: '2026-01-23T11:00:00Z',
    updatedAt: '2026-01-23T11:00:00Z',
  },
  {
    id: 'q-fiz-2',
    subjectId: 'sub-fiz',
    topic: 'Rad, energija i snaga',
    categoryId: 'cat-fiz-meh',
    categoryPath: ['Fizika', 'Mehanika kretanja i sila'],
    tags: ['mehanicki-rad', 'sila', 'put', 'dzul', 'ix-razred'],
    questionText: 'Dizalica podiže teret mase m = 200 kg na visinu h = 5 m konstantnom brzinom (uz g ≈ 10 m/s²). Koliki mehanički rad izvrši dizalica?',
    options: [
      { id: 'A', text: '1 000 J' },
      { id: 'B', text: '5 000 J' },
      { id: 'C', text: '10 000 J' },
      { id: 'D', text: '20 000 J' },
    ],
    correctOptionId: 'C',
    points: 3,
    difficulty: 'intermediate',
    cognitiveDomain: 'application',
    explanation: 'Sila dizanja jednaka je težini tereta: F = m * g = 200 kg * 10 m/s² = 2 000 N. Mehanički rad je A = F * h = 2 000 N * 5 m = 10 000 J (10 kJ).',
    authorName: 'Prof. Damir Kovačević',
    isActive: true,
    createdAt: '2026-01-23T11:30:00Z',
    updatedAt: '2026-01-23T11:30:00Z',
  },
  // DODATNA PITANJA ZA BAZU (AI TUTOR PREPORUČENI ZADACI)
  {
    id: 'q-mat-5',
    subjectId: 'sub-mat',
    topic: 'Linearne jednačine i nejednačine',
    categoryId: 'cat-mat-alg',
    categoryPath: ['Matematika', 'Linearne jednačine i nejednačine'],
    tags: ['linearne-jednacine', 'razlomci', 'algebarski-izrazi', 'ix-razred'],
    questionText: 'Riješi linearnu jednačinu sa razlomcima: (x + 1)/2 - (x - 1)/3 = 2. Koje je tačno rješenje za x?',
    options: [
      { id: 'A', text: 'x = 5' },
      { id: 'B', text: 'x = 7' },
      { id: 'C', text: 'x = 9' },
      { id: 'D', text: 'x = 3' },
    ],
    correctOptionId: 'B',
    points: 3,
    difficulty: 'intermediate',
    cognitiveDomain: 'application',
    explanation: 'Množenjem cijele jednačine sa NZS(2, 3) = 6 dobijamo: 3(x + 1) - 2(x - 1) = 12 => 3x + 3 - 2x + 2 = 12 => x + 5 = 12 => x = 7.',
    authorName: 'Prof. Damir Kovačević',
    isActive: true,
    createdAt: '2026-01-24T09:00:00Z',
    updatedAt: '2026-01-24T09:00:00Z',
  },
  {
    id: 'q-mat-6',
    subjectId: 'sub-mat',
    topic: 'Geometrijska tijela (Prizma, Valjak, Kupa)',
    categoryId: 'cat-mat-tijela',
    categoryPath: ['Matematika', 'Geometrijska tijela'],
    tags: ['geometrija', 'kupa', 'zapremina', 'poluprecnik', 'visina'],
    questionText: 'Prava kupa ima poluprečnik osnove r = 6 cm i visinu H = 8 cm. Kolika je zapremina V ove kupe?',
    options: [
      { id: 'A', text: '48π cm³' },
      { id: 'B', text: '96π cm³' },
      { id: 'C', text: '288π cm³' },
      { id: 'D', text: '36π cm³' },
    ],
    correctOptionId: 'B',
    points: 3,
    difficulty: 'intermediate',
    cognitiveDomain: 'application',
    explanation: 'Formula za zapreminu kupe je V = (1/3) * B * H = (1/3) * r²π * H = (1/3) * 36π * 8 = 12π * 8 = 96π cm³.',
    authorName: 'Prof. Damir Kovačević',
    isActive: true,
    createdAt: '2026-01-24T09:30:00Z',
    updatedAt: '2026-01-24T09:30:00Z',
  },
  {
    id: 'q-bhs-5',
    subjectId: 'sub-bhs',
    topic: 'Sintaksa složene rečenice',
    categoryId: 'cat-bhs-sint',
    categoryPath: ['B/H/S jezik i književnost', 'Sintaksa složene rečenice'],
    tags: ['sintaksa', 'zavisne-recenice', 'uzrocna', 'veznici'],
    questionText: 'Koji veznik u navedenoj rečenici povezuje zavisnu uzročnu rečenicu sa glavnom? "Učenici su pohvaljeni jer su pokazali izuzetno znanje na probnoj maturi."',
    options: [
      { id: 'A', text: 'čim' },
      { id: 'B', text: 'jer' },
      { id: 'C', text: 'iako' },
      { id: 'D', text: 'kako' },
    ],
    correctOptionId: 'B',
    points: 2,
    difficulty: 'basic',
    cognitiveDomain: 'knowledge',
    explanation: 'Veznik "jer" je tipičan pravi uzročni veznik koji iskazuje stvarni razlog ili uzrok vršenja radnje glavne rečenice.',
    authorName: 'Prof. Lejla Babić',
    isActive: true,
    createdAt: '2026-01-24T10:00:00Z',
    updatedAt: '2026-01-24T10:00:00Z',
  },
  {
    id: 'q-deu-4',
    subjectId: 'sub-deu',
    topic: 'Grammatik (Passiv & Modalverben)',
    categoryId: 'cat-deu-gram',
    categoryPath: ['Deutsch als Fremdsprache (DaF / DSD I)', 'Grammatik (Perfekt, Präteritum, Modalverben)'],
    tags: ['deutsch', 'passiv', 'werden', 'partizip-2', 'dsd-1'],
    questionText: 'Welche Passivform im Präsens ist korrekt? "Die Prüfungsaufgaben _______ von der Kommission korrigiert."',
    options: [
      { id: 'A', text: 'wird' },
      { id: 'B', text: 'werden' },
      { id: 'C', text: 'wurden' },
      { id: 'D', text: 'worden' },
    ],
    correctOptionId: 'B',
    points: 2,
    difficulty: 'intermediate',
    cognitiveDomain: 'application',
    explanation: 'Subjekt je u množini ("die Prüfungsaufgaben"), pa glagol "werden" u 3. licu množine prezenta glasi "werden": "werden korrigiert".',
    authorName: 'Frau Sabine Müller (DaF/DSD)',
    isActive: true,
    createdAt: '2026-01-24T10:30:00Z',
    updatedAt: '2026-01-24T10:30:00Z',
  },
  {
    id: 'q-eng-3',
    subjectId: 'sub-eng',
    topic: 'Passive Voice & Modals',
    categoryId: 'cat-eng-gram',
    categoryPath: ['English Language', 'Grammar'],
    tags: ['passive-voice', 'present-simple', 'grammar', 'ix-razred'],
    questionText: 'Rewrite in passive: "Teachers prepare official exam papers every spring."',
    options: [
      { id: 'A', text: 'Official exam papers are prepared by teachers every spring.' },
      { id: 'B', text: 'Official exam papers were prepared by teachers every spring.' },
      { id: 'C', text: 'Official exam papers are preparing by teachers every spring.' },
      { id: 'D', text: 'Official exam papers prepare by teachers every spring.' },
    ],
    correctOptionId: 'A',
    points: 2,
    difficulty: 'intermediate',
    cognitiveDomain: 'application',
    explanation: 'Present Simple Passive is formed with am/is/are + past participle (are prepared).',
    authorName: 'Prof. Lejla Babić',
    isActive: true,
    createdAt: '2026-01-24T11:00:00Z',
    updatedAt: '2026-01-24T11:00:00Z',
  },
];

export const initialExamSessions: ExamSession[] = [
  {
    id: 'sess-bhs-01',
    title: 'Eksterna matura IX razred: B/H/S jezik i književnost',
    description: 'Zvanični ispit eksterne mature za učenike IX razreda Internationale Deutsche Schule Sarajevo prema ispitnom katalogu PPZ KS.',
    subjectId: 'sub-bhs',
    subjectName: 'Bosanski, hrvatski, srpski jezik i književnost',
    examDate: '2026-06-15',
    startTime: '09:00',
    endDate: '2026-06-15',
    endTime: '10:30',
    durationMinutes: 90,
    roomNumber: 'Učionica 101 (Kabinet jezika)',
    location: 'IDSS Kampus, I sprat',
    maxCandidates: 25,
    status: 'scheduled',
    candidateCount: 20,
    commission: {
      president: 'Prof. dr. Ismar Hadžiosmanović',
      supervisor1: 'Frau Sabine Müller',
      supervisor2: 'Prof. Denis Karić',
      evaluator: 'Prof. Lejla Babić',
    },
    poolConfig: {
      categories: ['Morfologija i glagolski oblici', 'Pravopis i glasovne promjene', 'Književnost i lektira IX razreda'],
      tags: ['standardni-jezik', 'ix-razred', 'matura-2026'],
      difficultyDistribution: { basic: 50, intermediate: 35, advanced: 15 },
      questionCount: 20,
      shuffleQuestions: true,
    },
    rules: {
      passingThresholdPercent: 50,
      calculatorAllowed: false,
      formulaSheetAllowed: false,
      penaltyForWrongAnswers: false,
      allowedTools: ['Plava hemijska olovka', 'Učenička knjižica / ID kartica'],
      notes: 'Zabranjeno unošenje rječnika i mobilnih telefona ili pametnih satova.',
    },
    notes: 'Kandidati IX razreda moraju biti ispred sale 30 minuta prije početka sa važećom identifikacijom.',
  },
  {
    id: 'sess-mat-01',
    title: 'Eksterna matura IX razred: Matematika',
    description: 'Standardizovani ispit eksterne mature iz matematike za deveti razred (linearna algebra, Pitagorina teorema, geometrijska tijela).',
    subjectId: 'sub-mat',
    subjectName: 'Matematika',
    examDate: '2026-06-17',
    startTime: '09:00',
    endDate: '2026-06-17',
    endTime: '10:30',
    durationMinutes: 90,
    roomNumber: 'Učionica 102 (Kabinet matematike i fizike)',
    location: 'IDSS Kampus, I sprat',
    maxCandidates: 25,
    status: 'scheduled',
    candidateCount: 20,
    commission: {
      president: 'Prof. dr. Ismar Hadžiosmanović',
      supervisor1: 'Prof. Damir Kovačević',
      supervisor2: 'Frau Sabine Müller',
      evaluator: 'Prof. Jasna Halilović',
    },
    poolConfig: {
      categories: ['Linearne jednačine i nejednačine', 'Pitagorina teorema i geometrija', 'Geometrijska tijela', 'Procenti, proporcije i statistika'],
      tags: ['algebra', 'pitagorina-teorema', 'ix-razred'],
      difficultyDistribution: { basic: 40, intermediate: 45, advanced: 15 },
      questionCount: 20,
      shuffleQuestions: true,
    },
    rules: {
      passingThresholdPercent: 50,
      calculatorAllowed: false,
      formulaSheetAllowed: true,
      penaltyForWrongAnswers: false,
      allowedTools: ['Geometrijski pribor (lenjir, trougao, šestar)', 'Službena tablica osnovnih formula PPZ'],
      notes: 'Ispit se radi isključivo hemijskom olovkom, grafitna olovka dozvoljena samo za konstrukcijske crteže.',
    },
    notes: 'Dozvoljen osnovni pribor za geometriju i plava hemijska olovka.',
  },
  {
    id: 'sess-deu-01',
    title: 'Eksterna matura IX razred: Njemački jezik / Deutsch (DSD I)',
    description: 'Specijalizovani ispit iz njemačkog jezika za deveti razred Internationale Deutsche Schule Sarajevo usklađen sa DSD I standardima.',
    subjectId: 'sub-deu',
    subjectName: 'Njemački jezik / Deutsch (DSD I / DaF)',
    examDate: '2026-06-18',
    startTime: '09:00',
    endDate: '2026-06-18',
    endTime: '10:30',
    durationMinutes: 90,
    roomNumber: 'Učionica 103 (Deutsche Bibliothek & Sprachlabor)',
    location: 'IDSS Kampus, II sprat',
    maxCandidates: 25,
    status: 'scheduled',
    candidateCount: 20,
    commission: {
      president: 'Mag. Thomas Weber (Direktor škole)',
      supervisor1: 'Frau Sabine Müller (DaF/DSD)',
      supervisor2: 'Prof. Lejla Babić',
      evaluator: 'Dr. Klaus Becker (DSD Fachberater)',
    },
    poolConfig: {
      categories: ['Grammatik (Perfekt, Präteritum, Modalverben)', 'Nebensätze (weil, dass, wenn, obwohl)', 'Leseverstehen & Wortschatz (DSD I Niveau A2/B1)'],
      tags: ['deutsch', 'dsd-1', 'a2-b1', 'idss'],
      difficultyDistribution: { basic: 40, intermediate: 40, advanced: 20 },
      questionCount: 20,
      shuffleQuestions: true,
    },
    rules: {
      passingThresholdPercent: 50,
      calculatorAllowed: false,
      formulaSheetAllowed: false,
      penaltyForWrongAnswers: false,
      allowedTools: ['Plava hemijska olovka'],
      notes: 'Ispit obuhvata gramatički dio, leksiku i razumijevanje pročitanog teksta prema DSD I kriterijima.',
    },
    notes: 'IDSS ispitni certifikat se izdaje zajedno sa kantonalnim uvjerenjem.',
  },
  {
    id: 'sess-eng-01',
    title: 'Eksterna matura IX razred: Engleski jezik',
    description: 'Ispit iz engleskog jezika za IX razred na nivou A2/B1 prema Zajedničkom evropskom referentnom okviru za jezike.',
    subjectId: 'sub-eng',
    subjectName: 'Engleski jezik',
    examDate: '2026-06-19',
    startTime: '10:00',
    endDate: '2026-06-19',
    endTime: '11:30',
    durationMinutes: 90,
    roomNumber: 'Učionica 204 (Multimedijalni kabinet)',
    location: 'IDSS Kampus, II sprat',
    maxCandidates: 25,
    status: 'scheduled',
    candidateCount: 20,
    commission: {
      president: 'Prof. Sanela Hodžić',
      supervisor1: 'Prof. Enver Čaušević',
      supervisor2: 'Prof. Selma Oruč',
      evaluator: 'Prof. Lejla Babić',
    },
    poolConfig: {
      categories: ['Grammar', 'Vocabulary & Reading Comprehension'],
      tags: ['a2-b1', 'grammar', 'ix-razred'],
      difficultyDistribution: { basic: 40, intermediate: 45, advanced: 15 },
      questionCount: 20,
      shuffleQuestions: true,
    },
    rules: {
      passingThresholdPercent: 50,
      calculatorAllowed: false,
      formulaSheetAllowed: false,
      penaltyForWrongAnswers: false,
      allowedTools: ['Plava hemijska olovka'],
      notes: 'Audio slušni segment ispita počinje tačno u 10:10 bez prekidanja.',
    },
    notes: 'Audio segment ispita počinje tačno u 10:10. Vrata sale se zaključavaju u 10:00.',
  },
];

export const initialAttempts: StudentAttempt[] = [
  {
    id: 'att-sim-recent-mat',
    studentId: 'user-student-1',
    studentName: 'Amar Hadžić',
    subjectId: 'sub-mat',
    subjectName: 'Matematika',
    scoreAchieved: 65,
    maxScore: 100,
    percentage: 65,
    isPassed: true,
    durationSeconds: 2900,
    answers: {
      'q-mat-1': 'A', // Netačno (tačno je B: x = 9, odabrao A: x = 5) - Linearne jednačine
      'q-mat-2': 'A', // Tačno - Pitagorina teorema
      'q-mat-3': 'A', // Netačno (tačno je B: 90π cm³, odabrao A: 60π cm³) - Geometrijska tijela
      'q-mat-4': 'B', // Tačno - Procenti
      'q-mat-5': 'A', // Netačno (tačno je B: x = 7, odabrao A: x = 5) - Linearne jednačine sa razlomcima
    },
    completedAt: '2026-03-25T16:40:00Z',
    isSimulation: true,
    reviewNotes: 'Uočene poteškoće pri rješavanju linearnih jednačina sa zagradama i razlomcima, te pri računanju zapremine oblih geometrijskih tijela.',
  },
  {
    id: 'att-sim-recent-fiz',
    studentId: 'user-student-1',
    studentName: 'Amar Hadžić',
    subjectId: 'sub-fiz',
    subjectName: 'Fizika',
    scoreAchieved: 50,
    maxScore: 100,
    percentage: 50,
    isPassed: true,
    durationSeconds: 2400,
    answers: {
      'q-fiz-1': 'C', // Tačno - Ohmov zakon
      'q-fiz-2': 'A', // Netačno (tačno je C: 10 000 J, odabrao A: 1 000 J - zaboravljen faktor visine/gravitacije)
    },
    completedAt: '2026-03-24T14:10:00Z',
    isSimulation: true,
    reviewNotes: 'Graničan rezultat na probnom ispitu iz fizike. Potrebno utvrditi formule za mehanički rad, snagu i gravitacionu silu.',
  },
  {
    id: 'att-1',
    studentId: 'user-student-1',
    studentName: 'Amar Hadžić',
    subjectId: 'sub-mat',
    subjectName: 'Matematika',
    scoreAchieved: 92,
    maxScore: 100,
    percentage: 92,
    isPassed: true,
    durationSeconds: 3120,
    answers: { 'q-mat-1': 'B', 'q-mat-2': 'A', 'q-mat-3': 'B', 'q-mat-4': 'B' },
    completedAt: '2026-03-20T14:35:00Z',
    isSimulation: true,
    reviewNotes: 'Izvanredno poznavanje gradiva IX razreda: linearne jednačine, Pitagorina teorema i računanje zapremine valjka.',
  },
  {
    id: 'att-2',
    studentId: 'user-student-1',
    studentName: 'Amar Hadžić',
    subjectId: 'sub-bhs',
    subjectName: 'Bosanski, hrvatski, srpski jezik i književnost',
    scoreAchieved: 85,
    maxScore: 100,
    percentage: 85,
    isPassed: true,
    durationSeconds: 2750,
    answers: { 'q-bhs-1': 'B', 'q-bhs-2': 'A', 'q-bhs-3': 'B', 'q-bhs-4': 'B' },
    completedAt: '2026-03-22T11:15:00Z',
    isSimulation: true,
    reviewNotes: 'Odličan rezultat na testu iz maternjeg jezika za IX razred. Tačno prepoznati glagolski oblici i zavisne rečenice.',
  },
  {
    id: 'att-3',
    studentId: 'user-student-1',
    studentName: 'Amar Hadžić',
    subjectId: 'sub-deu',
    subjectName: 'Njemački jezik / Deutsch (DSD I / DaF)',
    scoreAchieved: 96,
    maxScore: 100,
    percentage: 96,
    isPassed: true,
    durationSeconds: 2600,
    answers: { 'q-deu-1': 'B', 'q-deu-2': 'B', 'q-deu-3': 'B' },
    completedAt: '2026-03-23T15:20:00Z',
    isSimulation: true,
    reviewNotes: 'Izvanredan nivo njemačkog jezika (DSD I priprema IDSS). Gramatika perfekta i zavisnih rečenica savladana sa maksimalnim bodovima.',
  },
  {
    id: 'att-4',
    studentId: 'user-student-2',
    studentName: 'Sarah Mešić',
    subjectId: 'sub-eng',
    subjectName: 'Engleski jezik',
    scoreAchieved: 95,
    maxScore: 100,
    percentage: 95,
    isPassed: true,
    durationSeconds: 2400,
    answers: { 'q-eng-1': 'A', 'q-eng-2': 'B' },
    completedAt: '2026-03-24T16:00:00Z',
    isSimulation: true,
    reviewNotes: 'Izvanredno poznavanje gramatičkih struktura A2/B1 nivoa za deveti razred.',
  },
];

export const initialAccommodations: StudentAccommodation[] = [
  {
    id: 'acc-1',
    studentId: 'user-student-3',
    studentName: 'Dino Begić',
    className: 'IX-2 (9b)',
    type: 'extra_time_25',
    typeLabel: 'Dodatno vrijeme za rad (+25%)',
    legalBasis: 'Član 14. stav 2. Pravilnika o inkluzivnom obrazovanju u osnovnim školama KS',
    description: 'Kandidatu IX razreda se odobrava produženje trajanja ispita za 25% (dodatna 22.5 minuta na ispitu od 90 min) uz odobrenje Stručnog tima IDSS.',
    approvedBy: 'Prof. Lejla Babić (Pedagog-psiholog IDSS)',
    approvedAt: '2026-02-10T11:00:00Z',
    isActive: true,
  },
  {
    id: 'acc-2',
    studentId: 'user-student-4',
    studentName: 'Emina Džafić',
    className: 'IX-2 (9b)',
    type: 'large_font',
    typeLabel: 'Prilagođeni font i format (A3 / 16pt)',
    legalBasis: 'Član 15. Pravilnika o prilagodbi ispitnih materijala za učenike IX razreda',
    description: 'Ispitni test za IX razred se štampa u formatu A3 sa uvećanim fontom 16pt i pojačanim kontrastom grafičkih elemenata.',
    approvedBy: 'Prof. Lejla Babić (Pedagog-psiholog IDSS)',
    approvedAt: '2026-02-12T14:30:00Z',
    isActive: true,
  },
];

export const initialRegulations: ComplianceRegulation[] = [
  {
    id: 'reg-1',
    actTitle: 'Zakon o osnovnom odgoju i obrazovanju Kantona Sarajevo',
    articleReference: 'Član 88. - Eksterna procjena znanja i eksterna matura',
    requirementSummary: 'Učenici koji završavaju deveti (IX) razred osnovne škole obavezni su polagati eksternu maturu prema standardiziranim ispitnim katalozima Prosvjetno-pedagoškog zavoda KS.',
    category: 'organizacija',
    status: 'compliant',
    responsiblePerson: 'Mag. Thomas Weber (Direktor škole)',
    lastVerifiedAt: '2026-03-01T10:00:00Z',
    notes: 'Školski odbor IDSS usvojio godišnji plan provođenja eksterne mature za IX razred na sjednici 15.10.2025.',
  },
  {
    id: 'reg-2',
    actTitle: 'Pravilnik o organizaciji i provođenju eksterne mature u osnovnim školama KS',
    articleReference: 'Član 12. - Tajnost i sigurnost ispitnih materijala',
    requirementSummary: 'Ispitni materijali i testovi za IX razred moraju se čuvati u sefu ustanove pod ključem direktora i predsjednika Ispitne komisije do 30 minuta prije početka ispita.',
    category: 'sigurnost_testova',
    status: 'compliant',
    responsiblePerson: 'Prof. dr. Ismar Hadžiosmanović',
    lastVerifiedAt: '2026-03-15T09:00:00Z',
    notes: 'Sef u direkciji IDSS verifikovan od strane kantonalne prosvjetne inspekcije.',
  },
  {
    id: 'reg-3',
    actTitle: 'Pravilnik o radu ispitnih komisija u osnovnoj školi',
    articleReference: 'Član 19. - Imenovanje dežurnih nastavnika za IX razred',
    requirementSummary: 'Dežurni nastavnik u ispitnoj sali ne može biti nastavnik koji predaje predmet koji se polaže u tom odjeljenju devetog razreda.',
    category: 'komisije',
    status: 'compliant',
    responsiblePerson: 'Prof. Lejla Babić (Pedagog-psiholog)',
    lastVerifiedAt: '2026-03-20T12:00:00Z',
    notes: 'Unakrsni raspored dežurstava IDSS usklađen sa satnicom i predmetnim nastavnicima.',
  },
  {
    id: 'reg-4',
    actTitle: 'Pravilnik o inkluzivnom obrazovanju u osnovnim školama Kantona Sarajevo',
    articleReference: 'Član 33. - Prilagodba ispitne procedure za IX razred',
    requirementSummary: 'Pedagoško-psihološka služba dužna je donijeti rješenja o prilagodbi ispita za učenike s posebnim potrebama u IX razredu najkasnije 60 dana prije održavanja mature.',
    category: 'inkluzija',
    status: 'compliant',
    responsiblePerson: 'Prof. Lejla Babić (Pedagog-psiholog)',
    lastVerifiedAt: '2026-02-15T15:00:00Z',
    notes: 'Za sve evidentirane učenike devetog razreda IDSS izdata su pojedinačna rješenja i obaviješteni roditelji.',
  },
  {
    id: 'reg-5',
    actTitle: 'Pravila i kurikulum Internationale Deutsche Schule Sarajevo (IDSS)',
    articleReference: 'Član 24. - Dvojezični nastavni program i DSD standardi',
    requirementSummary: 'Internationale Deutsche Schule Sarajevo provodi eksternu maturu uz integraciju pripreme za Deutsches Sprachdiplom I (DSD I) za sve učenike IX razreda.',
    category: 'organizacija',
    status: 'compliant',
    responsiblePerson: 'Frau Sabine Müller (DaF/DSD)',
    lastVerifiedAt: '2026-03-22T08:30:00Z',
    notes: 'Kurikulum njemačkog jezika i nivo A2/B1 usklađeni sa zahtjevima njemačke Konferencije ministara obrazovanja (KMK).',
  },
  {
    id: 'reg-6',
    actTitle: 'Ispitni kalendar Ministarstva za odgoj i obrazovanje KS',
    articleReference: 'Član 4. - Rokovi verifikacije i unosa bodova za IX razred',
    requirementSummary: 'Škola je obavezna unijeti konačne bodove učenika IX razreda u centralni registar EMIS Ministarstva u roku od 48 sati nakon završetka ispita.',
    category: 'rokovi',
    status: 'compliant',
    responsiblePerson: 'Administrator IT sistema IDSS',
    lastVerifiedAt: '2026-03-25T14:00:00Z',
    notes: 'Elektronska razmjena podataka sa informacionim sistemom ministarstva testirana.',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-03-25T09:15:22Z',
    userId: 'user-superadmin-1',
    userEmail: 'direktor@idss.ba',
    userRole: 'superadmin',
    action: 'POSTAVKE_AŽURIRANE',
    entityType: 'SchoolSettings',
    entityId: 'settings',
    details: 'Ažuriran prag prolaznosti eksterne mature IX razreda (50%) i potvrđen sastav centralne ispitne komisije IDSS.',
    ipAddress: '192.168.1.10',
  },
  {
    id: 'log-2',
    timestamp: '2026-03-24T14:40:11Z',
    userId: 'user-admin-pedagog',
    userEmail: 'pedagog@idss.ba',
    userRole: 'admin',
    action: 'PRILAGODBA_EVIDENTIRANA',
    entityType: 'StudentAccommodation',
    entityId: 'acc-1',
    details: 'Odobrena prilagodba "Dodatno vrijeme 25%" za učenika Dino Begić (IX-2 / 9b).',
    ipAddress: '192.168.1.25',
  },
  {
    id: 'log-3',
    timestamp: '2026-03-23T11:20:05Z',
    userId: 'user-admin-deutsch',
    userEmail: 'deutsch@idss.ba',
    userRole: 'admin',
    action: 'PITANJE_DODANO',
    entityType: 'Question',
    entityId: 'q-deu-2',
    details: 'Dodano novo ispitno pitanje iz predmeta Njemački jezik (DSD I / DaF) za IX razred sa oznakom dsd-1.',
    ipAddress: '192.168.1.34',
  },
  {
    id: 'log-4',
    timestamp: '2026-03-22T08:50:44Z',
    userId: 'user-superadmin-1',
    userEmail: 'direktor@idss.ba',
    userRole: 'superadmin',
    action: 'ISPITNA_SESIJA_KONFIGURISANA',
    entityType: 'ExamSession',
    entityId: 'sess-bhs-01',
    details: 'Konfigurisan ispit eksterne mature B/H/S jezik za IX razred na dan 15.06.2026. sa bazenom pitanja iz nastavnog plana osnovne škole.',
    ipAddress: '192.168.1.10',
  },
];

export const initialBadges: BadgeDefinition[] = [
  // 1. Streak Badges
  {
    id: 'streak-bronze',
    title: 'Consistency Streak (3 dana)',
    titleDe: 'Lern-Serie (3 Tage)',
    titleEn: 'Consistency Streak (3 Days)',
    description: 'Vježbajte ili rješavajte ispite najmanje 3 dana uzastopno.',
    descriptionDe: 'Übe oder absolviere Prüfungen an mindestens 3 aufeinanderfolgenden Tagen.',
    descriptionEn: 'Practice questions or take exam simulations on at least 3 consecutive days.',
    category: 'streak',
    tier: 'bronze',
    iconName: 'Flame',
    maxProgress: 3,
    unit: 'dana',
  },
  {
    id: 'streak-silver',
    title: 'Consistency Streak (7 dana)',
    titleDe: 'Lern-Serie (7 Tage)',
    titleEn: 'Consistency Streak (7 Days)',
    description: 'Održite kontinuitet učenja kroz 7 uzastopnih dana bez prekida.',
    descriptionDe: 'Halte deine Lernserie über 7 aufeinanderfolgende Tage aufrecht.',
    descriptionEn: 'Maintain an unbroken 7-day study and exam practice streak.',
    category: 'streak',
    tier: 'silver',
    iconName: 'Flame',
    maxProgress: 7,
    unit: 'dana',
  },
  {
    id: 'streak-gold',
    title: 'Consistency Streak (14 dana)',
    titleDe: 'Lern-Serie (14 Tage)',
    titleEn: 'Consistency Streak (14 Days)',
    description: 'Zlatni šampionski niz: 14 uzastopnih dana pripreme za eksternu maturu.',
    descriptionDe: 'Goldene Meisterschaft: 14 aufeinanderfolgende Tage Prüfungsvorbereitung.',
    descriptionEn: 'Champion streak: 14 consecutive days of external exam preparation.',
    category: 'streak',
    tier: 'gold',
    iconName: 'Flame',
    maxProgress: 14,
    unit: 'dana',
  },

  // 2. Subject Mastery Badges
  {
    id: 'math-expert',
    title: 'Mathematics Expert',
    titleDe: 'Mathe-Experte (9. Klasse)',
    titleEn: 'Mathematics Expert',
    description: 'Ostvarite rezultat od 85%+ na najmanje 2 simulacije iz Matematike za IX razred.',
    descriptionDe: 'Erreiche mindestens 85% in zwei Mathematik-Simulationen der 9. Klasse.',
    descriptionEn: 'Score 85%+ on at least 2 Grade 9 Mathematics exam simulations.',
    category: 'subject',
    tier: 'gold',
    iconName: 'Calculator',
    maxProgress: 2,
    unit: 'ispita',
    subjectId: 'sub-mat',
  },
  {
    id: 'deutsch-meister',
    title: 'German DSD I Meister',
    titleDe: 'Deutsches Sprachdiplom Meister (DSD I)',
    titleEn: 'German DSD I Master',
    description: 'Ostvarite 90%+ na simulaciji iz Njemačkog jezika (DSD I / DaF kurikulum IDSS).',
    descriptionDe: 'Erziele 90%+ in der DSD I / DaF Abschlussprüfungssimulation.',
    descriptionEn: 'Achieve 90%+ in the German (DSD I / DaF) matriculation simulation.',
    category: 'subject',
    tier: 'gold',
    iconName: 'Languages',
    maxProgress: 1,
    unit: 'ispit',
    subjectId: 'sub-deu',
  },
  {
    id: 'bhs-scholar',
    title: 'B/H/S Jezikoslovac',
    titleDe: 'Bosnischer Sprachexperte',
    titleEn: 'B/H/S Language Scholar',
    description: 'Položite simulaciju B/H/S jezika sa 85%+ bodova (morfologija i lektira IX razreda).',
    descriptionDe: 'Bestehe die B/K/S Sprachsimulation mit über 85% der Gesamtpunkte.',
    descriptionEn: 'Score 85%+ in Bosnian/Croatian/Serbian language and literature.',
    category: 'subject',
    tier: 'silver',
    iconName: 'BookMarked',
    maxProgress: 1,
    unit: 'ispit',
    subjectId: 'sub-bhs',
  },
  {
    id: 'english-pro',
    title: 'English Linguist (A2/B1)',
    titleDe: 'Englisch-Sprachprofi (A2/B1)',
    titleEn: 'English Linguist (A2/B1)',
    description: 'Ostvarite 90%+ bodova na simulaciji ispita iz Engleskog jezika za IX razred.',
    descriptionDe: 'Erreiche 90%+ in der Englisch-Simulation für die 9. Klasse.',
    descriptionEn: 'Score 90%+ on the Grade 9 English language simulation.',
    category: 'subject',
    tier: 'silver',
    iconName: 'Compass',
    maxProgress: 1,
    unit: 'ispit',
    subjectId: 'sub-eng',
  },

  // 3. Practice Volume Badges
  {
    id: 'practice-pioneer',
    title: 'Practice Pioneer (15 zadataka)',
    titleDe: 'Fleißiger Übender (15 Aufgaben)',
    titleEn: 'Practice Pioneer (15 Questions)',
    description: 'Riješite i provjerite najmanje 15 zadataka u Vježbaonici ispitnih pitanja.',
    descriptionDe: 'Löse und überprüfe mindestens 15 Aufgaben im Übungsbereich.',
    descriptionEn: 'Solve and check at least 15 questions in the Question Practice bank.',
    category: 'practice',
    tier: 'bronze',
    iconName: 'Target',
    maxProgress: 15,
    unit: 'zadataka',
  },
  {
    id: 'practice-centurion',
    title: 'Practice Centurion (30 zadataka)',
    titleDe: 'Aufgaben-Meister (30 Aufgaben)',
    titleEn: 'Practice Centurion (30 Questions)',
    description: 'Riješite ukupno 30 zadataka iz ispitnih kataloga svih predmeta.',
    descriptionDe: 'Löse insgesamt 30 standardisierte Prüfungsaufgaben aus dem Katalog.',
    descriptionEn: 'Solve a total of 30 standardized exam questions from all subjects.',
    category: 'practice',
    tier: 'silver',
    iconName: 'CheckCheck',
    maxProgress: 30,
    unit: 'zadataka',
  },
  {
    id: 'solution-explorer',
    title: 'Analitičar rješenja (Metodika)',
    titleDe: 'Erklärungs-Forscher',
    titleEn: 'Solution Explorer',
    description: 'Pregledajte i analizirajte 8 metodičkih objašnjenja i rješenja u vježbaonici.',
    descriptionDe: 'Analysiere 8 didaktische Erklärungen und Lösungswege im Übungsmodus.',
    descriptionEn: 'Inspect and study 8 detailed pedagogical solution explanations.',
    category: 'practice',
    tier: 'bronze',
    iconName: 'Sparkles',
    maxProgress: 8,
    unit: 'rješenja',
  },

  // 4. Mastery & Excellence
  {
    id: 'perfectionist',
    title: 'Perfekcionista (100% rezultat)',
    titleDe: '100% Perfektionist',
    titleEn: 'Perfectionist (100% Score)',
    description: 'Ostvarite maksimalnih 100% bodova na zvaničnoj simulaciji ispita.',
    descriptionDe: 'Erreiche die Höchstpunktzahl von 100% in einer Prüfungssimulation.',
    descriptionEn: 'Achieve a flawless 100% score on any official exam simulation.',
    category: 'mastery',
    tier: 'diamond',
    iconName: 'Trophy',
    maxProgress: 1,
    unit: 'ispit',
  },
  {
    id: 'speed-demon',
    title: 'Brzina i preciznost',
    titleDe: 'Schnelligkeit & Präzision',
    titleEn: 'Speed & Precision',
    description: 'Završite simulaciju za manje od 45 minuta uz ostvarenih više od 80% bodova.',
    descriptionDe: 'Beende eine Prüfung in unter 45 Minuten mit über 80% Punkten.',
    descriptionEn: 'Complete a simulation in under 45 minutes with an 80%+ score.',
    category: 'challenge',
    tier: 'silver',
    iconName: 'Zap',
    maxProgress: 1,
    unit: 'ispit',
  },
  {
    id: 'all-rounder',
    title: 'Svestrani maturant',
    titleDe: 'Allround-Absolvent',
    titleEn: 'All-Round Scholar',
    description: 'Uspješno položite simulacije iz najmanje 3 različita ispitna predmeta.',
    descriptionDe: 'Bestehe Simulationen in mindestens 3 verschiedenen Prüfungsfächern.',
    descriptionEn: 'Pass exam simulations across at least 3 distinct subjects.',
    category: 'mastery',
    tier: 'gold',
    iconName: 'Award',
    maxProgress: 3,
    unit: 'predmeta',
  },
  {
    id: 'matura-ready',
    title: 'Potpuno spreman za maturu (85%+ prosjek)',
    titleDe: 'Abitur-Bereit (85%+ Gesamtdurchschnitt)',
    titleEn: 'Matura Ready (85%+ Overall)',
    description: 'Dostignite ukupni prosjek od najmanje 85% na svim položenim simulacijama.',
    descriptionDe: 'Erreiche einen Gesamtdurchschnitt von mindestens 85% in allen Fächern.',
    descriptionEn: 'Maintain an overall average score of at least 85% across all subjects.',
    category: 'mastery',
    tier: 'diamond',
    iconName: 'Trophy',
    maxProgress: 85,
    unit: '%',
  },
];

export const initialPracticeActivities: StudentPracticeActivity[] = [
  // 4-day streak for user-student-1 (Amar Hadžić)
  {
    id: 'act-1',
    studentId: 'user-student-1',
    type: 'question_answered',
    subjectId: 'sub-mat',
    questionId: 'q-mat-1',
    isCorrect: true,
    timestamp: '2026-03-20T10:15:00Z',
  },
  {
    id: 'act-2',
    studentId: 'user-student-1',
    type: 'question_answered',
    subjectId: 'sub-mat',
    questionId: 'q-mat-2',
    isCorrect: true,
    timestamp: '2026-03-20T10:20:00Z',
  },
  {
    id: 'act-3',
    studentId: 'user-student-1',
    type: 'solution_revealed',
    subjectId: 'sub-mat',
    questionId: 'q-mat-3',
    timestamp: '2026-03-20T10:25:00Z',
  },
  {
    id: 'act-4',
    studentId: 'user-student-1',
    type: 'simulation_completed',
    subjectId: 'sub-mat',
    timestamp: '2026-03-20T14:35:00Z',
  },
  {
    id: 'act-5',
    studentId: 'user-student-1',
    type: 'question_answered',
    subjectId: 'sub-bhs',
    questionId: 'q-bhs-1',
    isCorrect: true,
    timestamp: '2026-03-21T09:30:00Z',
  },
  {
    id: 'act-6',
    studentId: 'user-student-1',
    type: 'question_answered',
    subjectId: 'sub-bhs',
    questionId: 'q-bhs-2',
    isCorrect: true,
    timestamp: '2026-03-21T09:40:00Z',
  },
  {
    id: 'act-7',
    studentId: 'user-student-1',
    type: 'solution_revealed',
    subjectId: 'sub-bhs',
    questionId: 'q-bhs-3',
    timestamp: '2026-03-21T09:45:00Z',
  },
  {
    id: 'act-8',
    studentId: 'user-student-1',
    type: 'simulation_completed',
    subjectId: 'sub-bhs',
    timestamp: '2026-03-22T11:15:00Z',
  },
  {
    id: 'act-9',
    studentId: 'user-student-1',
    type: 'question_answered',
    subjectId: 'sub-deu',
    questionId: 'q-deu-1',
    isCorrect: true,
    timestamp: '2026-03-23T14:00:00Z',
  },
  {
    id: 'act-10',
    studentId: 'user-student-1',
    type: 'question_answered',
    subjectId: 'sub-deu',
    questionId: 'q-deu-2',
    isCorrect: true,
    timestamp: '2026-03-23T14:15:00Z',
  },
  {
    id: 'act-11',
    studentId: 'user-student-1',
    type: 'simulation_completed',
    subjectId: 'sub-deu',
    timestamp: '2026-03-23T15:20:00Z',
  },
  {
    id: 'act-12',
    studentId: 'user-student-1',
    type: 'question_answered',
    subjectId: 'sub-eng',
    questionId: 'q-eng-1',
    isCorrect: true,
    timestamp: '2026-03-24T16:10:00Z',
  },
  {
    id: 'act-13',
    studentId: 'user-student-1',
    type: 'solution_revealed',
    subjectId: 'sub-eng',
    questionId: 'q-eng-2',
    timestamp: '2026-03-24T16:15:00Z',
  },
  {
    id: 'act-14',
    studentId: 'user-student-1',
    type: 'question_answered',
    subjectId: 'sub-mat',
    questionId: 'q-mat-4',
    isCorrect: true,
    timestamp: '2026-03-24T16:30:00Z',
  },
  {
    id: 'act-15',
    studentId: 'user-student-1',
    type: 'question_answered',
    subjectId: 'sub-fiz',
    questionId: 'q-fiz-1',
    isCorrect: true,
    timestamp: '2026-03-24T16:45:00Z',
  },
  {
    id: 'act-16',
    studentId: 'user-student-1',
    type: 'solution_revealed',
    subjectId: 'sub-fiz',
    questionId: 'q-fiz-1',
    timestamp: '2026-03-24T16:46:00Z',
  },
  {
    id: 'act-17',
    studentId: 'user-student-1',
    type: 'question_answered',
    subjectId: 'sub-deu',
    questionId: 'q-deu-3',
    isCorrect: true,
    timestamp: '2026-03-24T17:00:00Z',
  },
  {
    id: 'act-18',
    studentId: 'user-student-1',
    type: 'solution_revealed',
    subjectId: 'sub-deu',
    questionId: 'q-deu-3',
    timestamp: '2026-03-24T17:02:00Z',
  },
];
