#!/usr/bin/env python3
"""Blueprint evidence (Sprint 07, PDL-026, AMB-10): matches every question of the official 2026 tests (C15 B/H/S B1 to B4,
C16 German 1A to 1D) to its catalogue task by word overlap (Jaccard over folded words) and prints a Markdown report.

Usage: python3 tools/blueprint-evidence/match_tests.py > docs/discovery/BLUEPRINT_EVIDENCE.md
Needs PyMuPDF (tools/canon-ingestion/requirements.txt). Reads only official test PDFs and the ingestion output;
the test PDFs contain no personal data (bar-code label areas are empty).
"""
import json
import re
import unicodedata
from pathlib import Path

import pymupdf

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "OSTALI-DOKUMENTI"
OUT = ROOT / "tools" / "canon-ingestion" / "output"


def words(text: str, minimum: int = 3) -> set[str]:
    folded = unicodedata.normalize("NFKD", text.lower())
    folded = "".join(c for c in folded if not unicodedata.combining(c))
    return set(re.findall(r"[a-z0-9]{%d,}" % minimum, folded))


def jaccard(a: set[str], b: set[str]) -> float:
    return len(a & b) / (len(a | b) or 1)


def pdf_text(name: str) -> str:
    with pymupdf.open(DOCS / name) as document:
        return "\n".join(page.get_text() for page in document)


def best(target: set[str], candidates: list[tuple[str, set[str]]]) -> tuple[str, float]:
    key, bag = max(candidates, key=lambda c: jaccard(target, c[1]))
    return key, jaccard(target, bag)


def bhs(lines: list[str]) -> None:
    records = json.loads((OUT / "bhs_language_literature.questions.json").read_text())["records"]
    tasks = [(r["id"], words(r["syntax"]["raw_text"])) for r in records]
    lines.append("## B/H/S (C15)\n")
    lines.append("Position = order in the test (the test restarts numbering for completion and matching). Score = word overlap.\n")
    lines.append("| Test | Position | Catalogue task | Score |")
    lines.append("|---|---|---|---|")
    for name in ("A - Test B1.pdf", "B - Test B2.pdf", "C - Test B3.pdf", "D - Test B4.pdf"):
        parts = re.split(r"\n\s*(\d{1,2})\.\s", pdf_text(name))
        position = 0
        for index in range(1, len(parts) - 1, 2):
            bag = words(parts[index + 1][:1500])
            if len(bag) < 5:
                continue
            position += 1
            key, score = best(bag, tasks)
            lines.append(f"| {name[4:-4]} | {position} | {key} | {score:.2f} |")
    lines.append("")


def german(lines: list[str]) -> None:
    records = json.loads((OUT / "german.questions.json").read_text())["records"]
    tasks = [(r["id"], words(r["syntax"]["raw_text"])) for r in records]
    items = [(f"{r['id']}#{i['item_number']}", words(i["raw_text"], 2)) for r in records for i in (r.get("logic") or {}).get("scored_items") or []]
    lines.append("## German (C16)\n")
    lines.append("| Test | Part | Catalogue task or items (score) |")
    lines.append("|---|---|---|")
    for letter in "ABCD":
        text = pdf_text(f"NJEMAČKI JEZIK - TEST 1{letter}.pdf")
        sections = re.split(r"\n(I|II|III|IV|V)\s", text)
        for index in range(1, len(sections) - 1, 2):
            part, body = sections[index], sections[index + 1]
            if part in ("III", "IV"):
                found = []
                pieces = re.split(r"\n\s*(\d{1,2})\.\s", body)
                for j in range(1, len(pieces) - 1, 2):
                    if pieces[j] == "0":
                        continue
                    key, score = best(words(pieces[j + 1][:250], 2), items if part == "IV" else tasks)
                    found.append(f"{key} ({score:.2f})")
                lines.append(f"| 1{letter} | {part} | {', '.join(found)} |")
            else:
                key, score = best(words(body), tasks)
                lines.append(f"| 1{letter} | {part} | {key} ({score:.2f}) |")
    lines.append("")


def main() -> None:
    lines = [
        "# Blueprint evidence: official 2026 tests matched to catalogue tasks",
        "",
        "Generated by `tools/blueprint-evidence/match_tests.py` (Sprint 07, PDL-026, AMB-10). Every question of the four",
        "official B/H/S tests and the four German tests of the school year 2025/26 is matched to the catalogue task with",
        "the largest word overlap. Low scores are short questions whose wording differs slightly; they were checked by",
        "reading. The blueprint in `config/exam-blueprints.json` lists, per position, the catalogue range observed here.",
        "",
    ]
    bhs(lines)
    german(lines)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
